function Hd = filterdesignfunc(low, high)
%FILTERDESIGNFUNC Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and DSP System Toolbox 23.2.
% Generated on: 02-Dec-2023 16:33:45

% FIR least-squares Bandpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency
% disp("------");
% disp("Difference:");
high-low;

N      = 22;         % Order
Fstop1 = low;        % First Stopband Frequency
Fpass1 = low + 10;   % First Passband Frequency
Fpass2 = high - 10;  % Second Passband Frequency
Fstop2 = high;       % Second Stopband FrequencyWstop1 = 0.01;  % First Stopband Weight
Wstop1 = 1;
Wpass  = 1;          % Passband Weight
Wstop2 = 1;       % Second Stopband Weight

freq_vec = [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2];

% Calculate the coefficients using the FIRLS function.
b  = firpm(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 0], [Wstop1 Wpass Wstop2]);
Hd = dfilt.dffir(b);

% [EOF]
